CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_title TEXT NOT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT now(),
    folder_id INTEGER
        REFERENCES noteful_folders(id) on DELETE CASCADE NOT NULL,
    content TEXT NOT NULL
)